URL_NETFLIX_LOGIN = "https://www.netflix.com/login"
URL_NETFLIX_CONTENT = "https://www.netflix.com/kr/title/"

AWS_S3_VIDEO_THUMBNAIL = "video/thumbnail/"
AWS_S3_NETFLIX_THUMBNAIL = AWS_S3_VIDEO_THUMBNAIL + "netflix/"

LOCAL_DATA_PATH = "data/"
LOCAL_NETFLIX_THUMBNAIL = LOCAL_DATA_PATH + AWS_S3_VIDEO_THUMBNAIL